creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - kms:
        - arn: arn:aws:kms:eu-west-1:861276079961:key/de348176-0652-48ec-add5-7d08ffa11a46
          aws_profile: admin@customer
