---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-apps-domain-tenant
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: flux-system-services-domain-components-override
  interval: 5m
  retryInterval: 3m
  path: ./domain/apps/talk-to-your-data/tenant
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-apps-domain-components
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: flux-apps-domain-tenant
  interval: 5m
  retryInterval: 3m
  path: ./domain/apps/talk-to-your-data/components
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-apps-domain-components-override
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: flux-apps-domain-tenant
  interval: 5m
  retryInterval: 3m
  path: ./clusters/eosdev2/override/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
