---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-prerequisites
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: system-services-components-override
  interval: 5m
  retryInterval: 3m
  path: ./domain/apps/${STRATIO_USE_CASE}/prerequisites
  prune: true
  sourceRef:
    kind: GitRepository
    name: keos-fleet
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: keos-runtime-info
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-components
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: apps-prerequisites
  interval: 5m
  retryInterval: 3m
  path: ./domain/apps/${STRATIO_USE_CASE}/components
  prune: true
  sourceRef:
    kind: GitRepository
    name: keos-fleet
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: keos-runtime-info
  patches:
    - patch: |
          apiVersion: kustomize.toolkit.fluxcd.io/v1
          kind: Kustomization
          metadata:
            name: all
          spec:
            decryption:
              provider: sops
              secretRef:
                name: sops-gpg
      target:
        kind: Kustomization
        labelSelector: app.kubernetes.io/sops-secret-provided=${SOPS_SECRET_PROVIDED}
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-components-override
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: apps-prerequisites
  interval: 5m
  retryInterval: 3m
  path: ./clusters/${CLUSTER_NAME}/override/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: keos-fleet
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: keos-runtime-info
