---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-secrets
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 5m
  retryInterval: 3m
  path: ./clusters/${CLUSTER_NAME}/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg