---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system-services-domain
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 5m
  retryInterval: 3m
  wait: true
  timeout: 15m
  path: ./domain/system-services/talk-to-your-data
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system-services-domain-components-override
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: flux-system-services-domain
  interval: 5m
  retryInterval: 3m
  path: ./clusters/eosdev2/override/system-services
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info