---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-apps-domain-base
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: flux-system-services-domain
  interval: 5m
  retryInterval: 3m
  path: ./domain/apps/talk-to-your-data/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-apps-domain-components
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: flux-apps-domain-base
  interval: 5m
  retryInterval: 3m
  path: ./domain/apps/talk-to-your-data/components
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
  patches:
    - patch: |
        $patch: delete
        apiVersion: all
        kind: all
        metadata:
          name: all
      target:
        labelSelector: toolkit.fluxcd.io/component=postgres
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-apps-domain-components-overrides
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: flux-apps-domain-components
  interval: 5m
  retryInterval: 3m
  path: ./clusters/eosdev2/overrides/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info

