apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stratio-datastores
resources:
  - rbac.yaml
  - namespace.yaml
  - sync.yaml
labels:
  - pairs:
      toolkit.fluxcd.io/domain: apps
