---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-rocket
spec:
  serviceAccountName: flux-apps
  dependsOn:
    - name: apps-pgbouncer
      namespace: stratio-datastores
    - name: apps-virtualizer
      namespace: stratio-apps
    - name: apps-dg-s3-agent
      namespace: stratio-datastores
    - name: apps-genai-gateway
      namespace: stratio-genai
    - name: apps-genai-api
      namespace: stratio-genai
  interval: 1m
  retryInterval: 3m
  path: ./components/rocket/${STRATIO_SIZE}
  prune: true
  sourceRef:
    kind: GitRepository
    name: keos-apps
    namespace: flux-system
  timeout: 15m
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: keos-runtime-info
