creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - kms:
        - arn: arn:aws:kms:eu-west-1:861276079961:key/11e9dd27-85ba-4856-b2e3-1aca70d55f23
          aws_profile: admin@customer
