---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-services-components
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 5m
  retryInterval: 3m
  wait: true
  timeout: 15m
  path: ./domain/system-services/${STRATIO_USE_CASE}
  prune: true
  sourceRef:
    kind: GitRepository
    name: keos-fleet
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: keos-runtime-info
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-services-components-override
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: system-services-components
  interval: 5m
  retryInterval: 3m
  path: ./clusters/${CLUSTER_NAME}/override/system-services
  prune: true
  sourceRef:
    kind: GitRepository
    name: keos-fleet
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: keos-runtime-info