---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-nginx-connectors-secrets
spec:
  serviceAccountName: flux-apps
  targetNamespace: stratio-apps
  interval: 5m
  retryInterval: 3m
  path: ./clusters/${CLUSTER_NAME}/secrets/nginx-connectors
  prune: true
  sourceRef:
    kind: GitRepository
    name: keos-fleet
    namespace: flux-system
  decryption:
    provider: sops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-nginx-connectors
spec:
  serviceAccountName: flux-apps
  dependsOn:
    - name: apps-nginx-connectors-secrets
  interval: 5m
  retryInterval: 3m
  path: ./components/nginx-connectors/${STRATIO_SIZE}
  prune: true
  sourceRef:
    kind: GitRepository
    name: keos-apps
    namespace: flux-system
  timeout: 15m
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: keos-runtime-info
