creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - kms:
        - arn: arn:aws:kms:eu-west-1:867344456191:key/15fc37ac-bc12-430c-963b-998de197cb3e
          aws_profile: admin@customer
