---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-dg-s3-agent-secrets
spec:
  serviceAccountName: flux-apps
  targetNamespace: stratio-datastores
  interval: 1m
  retryInterval: 5m
  path: ./clusters/${CLUSTER_NAME}/secrets/dg-s3-agent
  prune: true
  sourceRef:
    kind: GitRepository
    name: keos-fleet
    namespace: flux-system
  decryption:
    provider: sops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-dg-s3-agent
spec:
  serviceAccountName: flux-apps
  dependsOn:
    - name: apps-dg-s3-agent-secrets
    - name: apps-connectors-management
      namespace: stratio-apps
  interval: 1m
  retryInterval: 5m
  path: ./components/dg-s3-agent/${STRATIO_SIZE}
  prune: true
  sourceRef:
    kind: GitRepository
    name: keos-apps
    namespace: flux-system
  timeout: 15m
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: keos-runtime-info
