---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-dg-s3-agent-secrets
spec:
  serviceAccountName: flux-apps
  targetNamespace: stratio-datastores
  interval: 5m
  retryInterval: 3m
  path: ./clusters/${CLUSTER_NAME}/secrets/dg-s3-agent
  prune: true
  sourceRef:
    kind: GitRepository
    name: keos-fleet
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-dg-s3-agent
spec:
  serviceAccountName: flux-apps
  dependsOn:
    - name: apps-dg-s3-agent-secrets
  interval: 5m
  retryInterval: 3m
  path: ./components/dg-s3-agent/${STRATIO_SIZE}
  prune: true
  sourceRef:
    kind: GitRepository
    name: keos-apps
  timeout: 15m
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: keos-runtime-info
