---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-apps-tenant-base
  namespace: kube-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: flux-system-services-tenant
  interval: 5m
  retryInterval: 3m
  path: ./tenants/apps/talk-to-your-data/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-apps-tenant-components
  namespace: kube-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: flux-apps-tenant-base
  interval: 5m
  retryInterval: 3m
  path: ./tenants/apps/talk-to-your-data/components
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info