creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - kms:
        - arn: arn:aws:kms:eu-west-1:861276079961:key/5bea0afd-5cbd-4a2c-ab0b-a90b51a01905
          aws_profile: admin@customer
