creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - kms:
        - arn: arn:aws:kms:eu-west-1:867344456191:key/9d2e95f3-e663-4266-9682-3fbb2301f248
          aws_profile: admin@customer
