apiVersion: v1
kind: ConfigMap
metadata:
  name: 02-gosec-helm-chart-override-values
  namespace: keos-core
data:
  values.yaml: |-
    ---
    gosec-authz:
      config:
        DYPLON_CACHE_ENABLED: "true"