apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stratio-datastores
resources:
  - namespace.yaml
  - rbac.yaml
  - git.yaml
  - postgres
labels:
  - pairs:
      toolkit.fluxcd.io/domain: apps
