apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stratio-datastores
resources:
  - namespace.yaml
  - rbac.yaml
  - postgres
  - pgbouncer
  - postgres-agent
  - opensearch
  - opensearch-agent
  - dg-s3-agent
  - eureka-agent
labels:
  - pairs:
      toolkit.fluxcd.io/domain: apps
