apiVersion: v1
kind: Secret
metadata:
    name: customer-s3-secret
data:
    bundle: ENC[AES256_GCM,data:3WMFUsmuRc2Ii0gIPxEwJp90lNbK5oXoVCYZycn7vjWOGf3W1Se90xjSQhwCXy0/iDcLTVpaouUFb4CfITD5CPykxYVriF5TEkhM+HkNIIVJDM1yHpJLhSGEzORc/EqmNnePTtm14VssDBmDcumoPM4vr+bRindHi4DNbMHQtLYd/fIWIsFxHcb1GGKvHrhmI5xl3sKa6GUNWeFnUaOX4fVg5Qxs0cztK9kkF+9Z9k9snhKPuCU203uJ2jyKGnzFCZ9sjw==,iv:l9sv3V0VInJS9XJidT6D8uOmebbpyG7X7AcbETig04Q=,tag:OLq4BoFM5UKb91UxUu5kmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-14T09:28:55Z"
    mac: ENC[AES256_GCM,data:G1B8NpnRoC4u/ZUmnzPyyME9FLb/xcMaTV+3vBke0CSiGxYnQIf4oIGksmMFayml/jo6eIo3JxF24L3M8XEQZfS/pxBPkn9uawxVYaTbnT5QhZG/LbDlw+U5o5CICs2CDbxWFUnqjRwSQ6PnfANIG/KyrceHK7AkNXe3wPY0Opc=,iv:CEc4Q9HZFE/g/Ih4wDI8yvqYxwskVixTYTI9XWCPngI=,tag:BhHmujJYUeYyCzYdBBcMew==,type:str]
    pgp:
        - created_at: "2025-03-14T09:28:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA61fZLASMwvzARAAmVdChLNx54Cs6HkWoN8xditKKk+wzYO02T7QHRxhFi/I
            Z7ZHDeWpVQa/vFGVzwUnCzlEFQ2QP9mxz+OkvMMkEVZPCQeZcb7IifM8W9iOHQzk
            v4+Bd6uUhdzcs2K7yzDEFwjmz4GY6bh46OQPUHgQQUYhy8lg+zaBoyVfBuXK2biM
            62LpRT5A4uJcM7+Aq4EC8QFm/ZSax5Az0KxeZOXGhmrmEzqh/foLHifzpOkEC1jT
            3xfvHnEj4nUCaYTBnzdbIEXlBfrXKYiwlaEJwT67tJ7OzQ/dGnc6nrAkpUSswj1z
            LAok8ERhGStX1LNQiVb0IIwag/PG+8YQcphau3kE/j7i/+w6iB4JCGYuhg/I2Scv
            R3U0b1pTFwIf9JStLgMN+leXFxUmStnRyZ4VCLa4ENDHyhl23QfJefvdhYgPttYy
            S30ScXymZxSSLewbdPF8fhGvJJZHfe86eCzBPA5LNhw+vuZxZzzsTpyke0NxUu5x
            ndwJMDdJgjzul5FfCVLMU8+Vviq3wxibIyMhpKAplNGEKtVGGDKNcKc5kGv+6u9+
            l0HpQtxMZKDMhn1Z/FvURIIICxTOoJU0d9Y6vvvsx2HltE3VBKbxcpitC32SdQdq
            1HPnGbmsryauSbGenGBxB0ClaUJDMLqwmGU+gzjbKNbeiVhUSktRsqkzoagQ9pvS
            XgH45/8/eNHkgiaymXyq6TFwVnr41yQk1+OmmHOtyIUhSDMEr6UQbDWnJdVkNbX5
            uYbHYnoOpuq2NrAe4U0p1uHgVR0g6zFSak8BHvw+o5x5xyxUEVv9i34Jppli6Cw=
            =rPEQ
            -----END PGP MESSAGE-----
          fp: 1237C663B4C1D35144933583F0941B3EAFEA3837
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
