apiVersion: v1
kind: Secret
metadata:
    name: customer-s3-secret
data:
    bundle: ENC[AES256_GCM,data:w4oesxw3tP79UhebAn81WI+s/7xvqnUwHwmNpAzLFQWIbBClnv9RSUf/dSrXJUat/zPyIgJrYalDCXVGD9X9EatjqyATeiOzxqrzqLFWE9AVO4DurJaVpKCvJ+/k+M+RSrqoBHJVOVXgL1nDg0XYAHqG3gA8eRgFT/CRxpNfgnM7/l52Pk+dnTIlFALn3B0U8rLKUpytS9pzdiawmMAGa44NZjh+fT6D9TLhoFURBSaAgsruYvChUkB7ha6yPI4mX20HrCHUcmRQGAW4fxZq5fpauw/XX2Zw5OvII51xq2QWAdlo,iv:+r4pJcy4mcoAmP6lYmU2lDJ6U6/ZdXQiwTo0nrADjY8=,tag:auT+9FQApnj6flicmVvyoA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:861276079961:key/1632fb81-d379-4e34-b375-a5cfc3153b3f
          created_at: "2025-03-17T14:24:51Z"
          enc: AQICAHhk+kA2fOWvTgCUId2Uh84VZLAUbzw+Ho5G3NONrL9X6AGp+GI/di59KGZN8hJymDg5AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMGS3+ijtQorduM0phAgEQgDvZxs68ieIXBa7Am9IOBOl/NTVMaLl9tdoUayBM5F8R6+T/ol+KwDEuoKUqtFtVmpb3FyuCOLtbxtE5pg==
          aws_profile: admin@customer
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-17T14:24:51Z"
    mac: ENC[AES256_GCM,data:JCbNXzIa4/dfKjsC3ZthKo4fqi8uXM68XHiPNcq1+kpO6DCVxaHkkqdeSbOX2YE7aTZsTCXR1KswbmDx+M0CWn2MS1ekBUdhHgMVEjDPuMJQrMupzQIpl2hctSou67B3YDzB0+qb8tMlPFrF9BsPeK/1G9cuOJxChsX8Kcq4Hog=,iv:iyn2+DZVNptMYOSLFD8rRQ7KYkUvfqZ9QghaoPKTLh4=,tag:R4pkTQOI8J9pK0rzfqCm4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
