apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-pgbouncer
spec:
  serviceAccountName: flux-apps
  dependsOn:
    - name: flux-postgres
  interval: 5m
  retryInterval: 3m
  path: ./components/pgbouncer/${STRATIO_SIZE}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-apps
  timeout: 15m
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
