apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stratio-apps
resources:
  - sync.yaml
labels:
  - pairs:
      toolkit.fluxcd.io/domain: apps
      toolkit.fluxcd.io/component: virtualizer
