apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-apps-domain
  namespace: kube-system
spec:
  serviceAccountName: kustomize-controller
  dependsOn:
    - name: flux-system-services-domain
  interval: 12h
  retryInterval: 3m
  path: ./tenants/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
