creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - kms:
        - arn: arn:aws:kms:eu-west-1:861276079961:key/af5a3def-c451-4ff9-979b-d7c50c2d92e7
          aws_profile: admin@customer
