creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - kms:
        - arn: arn:aws:kms:eu-west-1:861276079961:key/1632fb81-d379-4e34-b375-a5cfc3153b3f
          aws_profile: admin@customer
