---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keos-runtime-info
  namespace: flux-system
  labels:
    toolkit.fluxcd.io/runtime: "true"
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: "Merge"
    replicator.v1.mittwald.de/replicate-to: ".*"
data:
  STRATIO_USE_CASE: "talk-to-your-data"
  STRATIO_SIZE: "S"
  GIT_BRANCH: "main"
  CLUSTER_NAME: "s-1234"
  CLUSTER_DOMAIN: "stratio.com"
  CONTAINER_REGISTRY_URL: "registry.com"
  CONTAINER_REGISTRY_IMAGES_REPOSITORY_PREFIX: "/universe-14.0"
  CONTAINER_REGISTRY_HELM_CHARTS_REPOSITORY_PREFIX: "/helm-14.0"