apiVersion: v1
kind: Secret
metadata:
    name: dg-s3-agent-s3
data:
    bundle: ENC[AES256_GCM,data:1dKz1b3+6peagu4qSmdkLqzsrEOamuNbLNpgGI9TVBoAX+i7AetOmhaiHvWg47+KqKvzhr1KB7WGg1MbWloCMg3HpoLSVaZ87OqpDXaJwvQr8Qbvdeyao/i5mfSsKHwKbLRlujYTOSryiH0zXdOT5WeiNcD5C2eFphVRF5yqf0fw+vQI5GYKAHtiNK17nf7xm8q6+HhoCiilBh1L2s3cph2H2hpwwZKuipkSE2AD8T1Wo0OleEBrBX0Q4EtzxeXy5U5nKTuR4h03j/BW/VuSDAowyh/wS6vEt3R2JE0FQjtFIg5F,iv:tN3THg3TC3bSdkQDJBO/QFZa2TdKRdOpyTYZYYmLzFI=,tag:V6pzj2iuXOVDTPKgT+jSUQ==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:861276079961:key/5bea0afd-5cbd-4a2c-ab0b-a90b51a01905
          created_at: "2025-03-07T13:00:52Z"
          enc: AQICAHiuI7tCdlNRw/YzStbqGFcieXeuUiIwtXlQEY4/0p+1LwH5zkJdX4oxMbsH1vWOdQhnAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMrCM6t7cejTr7lG1tAgEQgDtsaAmYlKSG3tBXj+UMFMSvsvJzXMwEzGYwaB5VKTKdh3NYTDxSy8J8miWa5/kZnzexGg5Otbp4cYHCJA==
          aws_profile: admin@customer
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-07T13:00:53Z"
    mac: ENC[AES256_GCM,data:jtr9MbwbcPyTg3I4dmiOK9GkgwCKSVEcRqWQTpyf9DNUyCipe/259jS+46lqznlWZKIfMF+XoTJ2ItO1wzvFWOqFfj4V2YSOL43lGeM/d8n8ErTbJHysSjNMyxm+b38bsenL87Vacce/78cxBsPifp9qN9SLH+dY+j/Lvpz+ohU=,iv:CeCh+hyG8CuBwDcckaLKC216Y1TpPcTd9AWwg5gU6JQ=,tag:+eiLugCI8QUWQeMabRSJKg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
