---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-genai-gateway
spec:
  serviceAccountName: flux-apps
  dependsOn:
    - name: apps-pgbouncer
      namespace: stratio-datastores
  interval: 1m
  retryInterval: 3m
  path: ./components/genai-gateway/${STRATIO_SIZE}
  prune: true
  sourceRef:
    kind: GitRepository
    name: keos-apps
    namespace: flux-system
  timeout: 15m
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: keos-runtime-info
