creation_rules:
  - path_regex: .*.yaml
    encrypted_regex: ^(data|stringData)$
    key_groups:
      - kms:
        - arn: arn:aws:kms:eu-west-1:891612546069:key/586842d1-2a84-45d4-8923-6b36230caaf4
          aws_profile: forselli@marketplace-customer@dev
