apiVersion: v1
kind: Secret
metadata:
    name: nginx-connectors-s3
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:l6IoiiUHYSp0MO8Vf9YIupumFUnFFKG1JKNkzg==,iv:MVvMcUPX5AFCZPgJJBD+u1HccDzI7JO1zaS4wyUnJDM=,tag:rmvEN/PNjBJn1bQb06purg==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ZY2elarT9GhcvItxxKcrHgJI+0z/i65ZeVCgu2jtQtZPuJPcI6X9cc16YsxGMLxyCQjfdqvVn1I=,iv:8QhWS0ZtMWRNFK/C8ngOCQqO2nRN+hh10hjJlXtARtk=,tag:yf34xpatNT7Xw4cgvt+5qw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:891612546069:key/586842d1-2a84-45d4-8923-6b36230caaf4
          created_at: "2025-03-05T11:51:32Z"
          enc: AQICAHiSNY/bVkb6ngmjvnoEOUZi/Ff70GRPR47ENwx2ZxgQNQHxXiNL/TUSrTcu1kWCgrpFAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMfjn9RDRH0mGPTCMFAgEQgDuhroRoZPJpPIICfO5WayEcYV4RcFO8YguFUzF+n94jZwyvPNxEstSUTLVmEwU+y1F7eoZ1bToP1y+D7Q==
          aws_profile: forselli@marketplace-customer@dev
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-05T11:51:33Z"
    mac: ENC[AES256_GCM,data:m7J3AYysAv/zKcdC1qlPnM2lJGDUhOC/6HJp2o7e3OH6kth/BxRPU5qqQQz9Mg+dDeuQlDMKG6bNQTMYQSw656ZQ6VX/8ru5QtjWmuJmA5DKMnr/gIYuNTQTWLQpKPOVibWLNA6bUCWV3589FiXWT+lb0bov1mqfhagcGA66Qnk=,iv:XtoqqMfniVerLQGR4GOQIeu218ODTs+x6p/nNs81xYo=,tag:H0xELQnhQUO3K0tQJHNZNg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
