apiVersion: v1
kind: Secret
metadata:
    name: nginx-connectors-s3
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:kt9YCrNuHGMzymPFA1Ye1NUHYEalvqEd4axNpw==,iv:rIMd/L8AXet8nE20JpwT+x43al7oBZqBnx1plTag0Zg=,tag:LrJ3WcVLPVAgzlsQ2JH98A==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:paV2ta8U4lF8z9Vhe3J7CxpJLRLlT2cm3B2vaYlF/H9q7f9lKY4Wws1cH5ayU+lyZGByl/BDBMY=,iv:7m8tJwqrm4eVmQ2AOyfv8pb2dyqTDMohNnB369Lt4tU=,tag:6l6SZLXMIwUjiWk84RZM3Q==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:891612546069:key/586842d1-2a84-45d4-8923-6b36230caaf4
          created_at: "2025-03-05T12:16:40Z"
          enc: AQICAHiSNY/bVkb6ngmjvnoEOUZi/Ff70GRPR47ENwx2ZxgQNQHkkK70uuTXAh7thdM4sCwmAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMrieMxSEwH3HTC/hDAgEQgDvD3GUFadPsBpXoNice4sCFFVhXJq4dD5pGaxFh5Nyd0S2TYfJ4EnPE4P6JPBl82r6aj8n2MmpGUMxRuQ==
          aws_profile: forselli@marketplace-customer@dev
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-05T12:16:40Z"
    mac: ENC[AES256_GCM,data:cqnzHYE9JQqeYzZrWKu2j6Tf3zxUDDbmzN5HIepI3qDWuVpmjXSVEI0PWkxywhBt79kfD9gXrhfeDXibKxhN4ESuh+HYoaRQR3hCgQUQ6AGaagKeqgz06ZJMQQe3o8rVYlBHaoxJu1PSzTtt+9YpCiFa8qO1uAsa8hKdM99L3hg=,iv:LnHBD2alukc0ymzrtuHwqZUl0uxlq1U7KyIivao62KE=,tag:xjbbrHNdHD4QulGYOo3TUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
