---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keos-runtime-info
  namespace: flux-system
  labels:
    toolkit.fluxcd.io/runtime: "true"
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: "Merge"
    replicator.v1.mittwald.de/replicate-to: ".*"
data:
  STRATIO_USE_CASE: "talk-to-your-data"
  STRATIO_SIZE: "_STRATIO_SIZE"
  GIT_BRANCH: "_GIT_BRANCH"
  CLUSTER_NAME: "_CLUSTER_NAME"
  CLUSTER_DOMAIN: "_CLUSTER_DOMAIN"
  CONTAINER_REGISTRY_URL: "_CONTAINER_REGISTRY_URL"
  CONTAINER_REGISTRY_REPOSITORY_PREFIX: "_CONTAINER_REGISTRY_REPOSITORY_PREFIX"
  HELM_REGISTRY_PROVIDER: "_HELM_REGISTRY_PROVIDER"
  HELM_REGISTRY_TYPE: "_HELM_REGISTRY_TYPE"
  HELM_REGISTRY_URL: "_HELM_REGISTRY_URL"
  HELM_REGISTRY_REPOSITORY_PREFIX: "_HELM_REGISTRY_REPOSITORY_PREFIX"
  SOPS_SECRET_PROVIDED: "_SOPS_SECRET_PROVIDED"
