---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-dg-s3-agent-secret
spec:
  serviceAccountName: flux-apps
  interval: 5m
  retryInterval: 3m
  path: ./clusters/${CLUSTER_NAME}/secrets/dg-s3-agent
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 15m
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-dg-s3-agent
spec:
  dependsOn:
    - name: flux-dg-s3-agent-secret
  serviceAccountName: flux-apps
  interval: 5m
  retryInterval: 3m
  path: ./components/dg-s3-agent/${STRATIO_SIZE}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-apps
  timeout: 15m
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
