---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-dg-s3-agent-secret
spec:
  serviceAccountName: flux-apps
  interval: 5m
  retryInterval: 3m
  path: ./clusters/${CLUSTER_NAME}/secrets/dg-s3-agent
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 15m
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-apps
spec:
  interval: 1m
  ref:
    branch: ${GIT_BRANCH}
  secretRef:
    name: flux-system
  url: https://github.com/forselli-stratio/keos-apps-test.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-dg-s3-agent
spec:
  dependsOn:
    - name: flux-dg-s3-agent-secret
  serviceAccountName: flux-apps
  interval: 5m
  retryInterval: 3m
  path: ./components/dg-s3-agent/${STRATIO_SIZE}
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-apps
  timeout: 15m
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info
