---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gosec-configs
spec:
  serviceAccountName: flux-system-services
  interval: 5m
  retryInterval: 2m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system-services
  path: components/gosec/configs/${STRATIO_USE_CASE}
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-runtime-info