---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-services-gosec-configs
spec:
  serviceAccountName: kustomize-controller
  interval: 5m
  retryInterval: 2m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: keos-system-services
  path: components/gosec/configs/${STRATIO_USE_CASE}
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: keos-runtime-info