---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-services-monitoring-configs
spec:
  serviceAccountName: kustomize-controller
  interval: 1m
  retryInterval: 2m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: keos-system-services
  path: components/monitoring/configs/${STRATIO_USE_CASE}
