---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stratio-panel-ui-configs
spec:
  serviceAccountName: flux-system-services
  interval: 5m
  retryInterval: 2m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system-services
  path: components/stratio-panel-ui/configs/${STRATIO_USE_CASE}
