---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keos-runtime-info
  namespace: flux-system
  labels:
    toolkit.fluxcd.io/runtime: "true"
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: "Merge"
    replicator.v1.mittwald.de/replicate-to: ".*"
data:
  STRATIO_USE_CASE: "talk-to-your-data"
  STRATIO_SIZE: "S"
  GIT_BRANCH: "main"
  CLUSTER_NAME: "eosdev2"
  CLUSTER_DOMAIN: "k8s.eosdev2.labs.stratio.com"
  CONTAINER_REGISTRY_URL: "qa.int.stratio.com:11443"
  CONTAINER_REGISTRY_IMAGES_REPOSITORY_PREFIX: ""
  HELM_REGISTRY_PROVIDER: "generic"
  HELM_REGISTRY_TYPE: "default"
  HELM_REGISTRY_URL: "qa.int.stratio.com"
  HELM_REGISTRY_HELM_CHARTS_REPOSITORY_PREFIX: "/repository/helm-all"
  SOPS_SECRET_PROVIDED: "true"
