apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stratio-apps
resources:
  - namespace.yaml
  - rbac.yaml
  - git.yaml
  - nginx-connectors
  - dg-s3-agent
labels:
  - pairs:
      toolkit.fluxcd.io/domain: apps
