apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stratio-apps
resources:
  - namespace.yaml
  - rbac.yaml
  - connectors-management
labels:
  - pairs:
      toolkit.fluxcd.io/domain: apps
